## Pandas (Data Manipulation and Analysis)
Read the data from the csv file

In [1]:
import pandas as pd
df = pd.read_csv('data.csv')
df.head(10)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
5  2023-01-06        B   54.0  Product3  192.0   West
6  2023-01-07        A   16.0  Product1  936.0   East
7  2023-01-08        C   89.0  Product1  488.0   West
8  2023-01-09        C   37.0  Product3  772.0   West
9  2023-01-10        A   22.0  Product2  834.0   West

Show data from the bottom

In [2]:
df.tail(9)

          Date Category  Value   Product  Sales Region
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

Describe the csv data

In [3]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

Showing data types of columns

In [4]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

Checking whether any column has null values

In [5]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

Checking how many null values are there in the dataset

In [6]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

Fill something at the place of null values.

In [7]:
filled_df = df.fillna(0)
filled_df.head(18)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West

Fill mean value of the column where null values are present

In [8]:
df['Value_fillna'] = df['Value'].fillna(df['Value'].mean())
df.head(18)

          Date Category  Value   Product  Sales Region  Value_fillna
0   2023-01-01        A   28.0  Product1  754.0   East     28.000000
1   2023-01-02        B   39.0  Product3  110.0  North     39.000000
2   2023-01-03        C   32.0  Product2  398.0   East     32.000000
3   2023-01-04        B    8.0  Product1  522.0   East      8.000000
4   2023-01-05        B   26.0  Product3  869.0  North     26.000000
5   2023-01-06        B   54.0  Product3  192.0   West     54.000000
6   2023-01-07        A   16.0  Product1  936.0   East     16.000000
7   2023-01-08        C   89.0  Product1  488.0   West     89.000000
8   2023-01-09        C   37.0  Product3  772.0   West     37.000000
9   2023-01-10        A   22.0  Product2  834.0   West     22.000000
10  2023-01-11        B    7.0  Product1  842.0  North      7.000000
11  2023-01-12        B   60.0  Product2    NaN   West     60.000000
12  2023-01-13        A   70.0  Product3  628.0  South     70.000000
13  2023-01-14        A   69.0  Product1  423.0   East     69.000000
14  2023-01-15        A   47.0  Product2  893.0   West     47.000000
15  2023-01-16        C    NaN  Product1  895.0  North     51.744681
16  2023-01-17        C   93.0  Product2  511.0  South     93.000000
17  2023-01-18        C    NaN  Product1  108.0   West     51.744681

Change the data type of the columns

In [9]:
df['Value_fillna'] = df['Value_fillna'].astype(int)
df.head()

         Date Category  Value   Product  Sales Region  Value_fillna
0  2023-01-01        A   28.0  Product1  754.0   East            28
1  2023-01-02        B   39.0  Product3  110.0  North            39
2  2023-01-03        C   32.0  Product2  398.0   East            32
3  2023-01-04        B    8.0  Product1  522.0   East             8
4  2023-01-05        B   26.0  Product3  869.0  North            26

Apply function on specific column

In [10]:
def square(num):
    return num*num

df['new_value'] = df['Value_fillna'].apply(square)
df.head()

         Date Category  Value   Product  Sales Region  Value_fillna  new_value
0  2023-01-01        A   28.0  Product1  754.0   East            28        784
1  2023-01-02        B   39.0  Product3  110.0  North            39       1521
2  2023-01-03        C   32.0  Product2  398.0   East            32       1024
3  2023-01-04        B    8.0  Product1  522.0   East             8         64
4  2023-01-05        B   26.0  Product3  869.0  North            26        676

Grouped columns to get mean of each group

In [11]:
grouped_mean = df.groupby('Category')['Value'].mean()
grouped_mean.head()

Category
A    48.357143
B    44.142857
C    59.842105
Name: Value, dtype: float64

Grouped specofic columns to get desires output in ascending or descending order

In [25]:
df.groupby('Product')['Sales'].sum().sort_values(ascending=True)

Product
Product2    7374.0
Product1    8623.0
Product3    9631.0
Name: Sales, dtype: float64

Aggregate multiple functions on grouped data

In [23]:
df.groupby(['Category','Product'])['Value'].agg(['mean', 'sum', 'max', 'min'])

                        mean    sum   max   min
Category Product
A        Product1  46.800000  234.0  69.0  16.0
         Product2  28.200000  141.0  47.0  17.0
         Product3  75.500000  302.0  96.0  43.0
B        Product1   9.000000   36.0  15.0   6.0
         Product2  73.000000  219.0  99.0  60.0
         Product3  51.857143  363.0  69.0  26.0
C        Product1  75.400000  377.0  97.0   2.0
         Product2  61.714286  432.0  93.0  32.0
         Product3  46.857143  328.0  82.0  11.0

Two different DataFrames to apply merge operations on them

In [28]:
import pandas as pd

customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "name": ["Amit", "Priya", "Rahul", "Neha", "Karan"],
    "city": ["Delhi", "Mumbai", "Pune", "Delhi", "Bangalore"]
})

orders = pd.DataFrame({
    "order_id": [5001, 5002, 5003, 5004, 5005],
    "customer_id": [101, 103, 104, 106, 102],
    "product": ["Laptop", "Phone", "Tablet", "Camera", "Headphones"],
    "amount": [70000, 20000, 15000, 30000, 5000]
})

In [29]:
customers

   customer_id   name       city
0          101   Amit      Delhi
1          102  Priya     Mumbai
2          103  Rahul       Pune
3          104   Neha      Delhi
4          105  Karan  Bangalore

In [30]:
orders

   order_id  customer_id     product  amount
0      5001          101      Laptop   70000
1      5002          103       Phone   20000
2      5003          104      Tablet   15000
3      5004          106      Camera   30000
4      5005          102  Headphones    5000

Inner merge operations

In [31]:
pd.merge(customers,orders, on='customer_id', how='inner')

   customer_id   name    city  order_id     product  amount
0          101   Amit   Delhi      5001      Laptop   70000
1          102  Priya  Mumbai      5005  Headphones    5000
2          103  Rahul    Pune      5002       Phone   20000
3          104   Neha   Delhi      5003      Tablet   15000

Outer merge operation

In [32]:
pd.merge(customers,orders, on='customer_id', how='outer')

   customer_id   name       city  order_id     product   amount
0          101   Amit      Delhi    5001.0      Laptop  70000.0
1          102  Priya     Mumbai    5005.0  Headphones   5000.0
2          103  Rahul       Pune    5002.0       Phone  20000.0
3          104   Neha      Delhi    5003.0      Tablet  15000.0
4          105  Karan  Bangalore       NaN         NaN      NaN
5          106    NaN        NaN    5004.0      Camera  30000.0

Left merge operation

In [33]:
pd.merge(customers,orders, on='customer_id', how='left')

   customer_id   name       city  order_id     product   amount
0          101   Amit      Delhi    5001.0      Laptop  70000.0
1          102  Priya     Mumbai    5005.0  Headphones   5000.0
2          103  Rahul       Pune    5002.0       Phone  20000.0
3          104   Neha      Delhi    5003.0      Tablet  15000.0
4          105  Karan  Bangalore       NaN         NaN      NaN

Right merge operation

In [35]:
pd.merge(customers,orders, on='customer_id', how='right')

   customer_id   name    city  order_id     product  amount
0          101   Amit   Delhi      5001      Laptop   70000
1          103  Rahul    Pune      5002       Phone   20000
2          104   Neha   Delhi      5003      Tablet   15000
3          106    NaN     NaN      5004      Camera   30000
4          102  Priya  Mumbai      5005  Headphones    5000

After that apply groupby on merge dataframe and apply agg function on it.

In [41]:
merged_df = pd.merge(customers, orders, on="customer_id", how="inner")
merged_df.groupby(['name','product'])['amount'].sum()

name   product
Amit   Laptop        70000
Neha   Tablet        15000
Priya  Headphones     5000
Rahul  Phone         20000
Name: amount, dtype: int64

In [42]:
merged_df.groupby(['name', 'customer_id', 'product'])['amount'].sum()

name   customer_id  product
Amit   101          Laptop        70000
Neha   104          Tablet        15000
Priya  102          Headphones     5000
Rahul  103          Phone         20000
Name: amount, dtype: int64